### ISSUE TITLE
Google map controls effected by Twitter Bootstrap styles

### ISSUE THREAD

**Issue by derekeder** [codeforamerica/councilmatic#30]
Adding this block to councilmatic.css should do the trick:

``` css
#map_canvas img {
  max-width: none;
}
```

Didn't want to add it in until we converted the styles from less to css.
